name: Mend

on: workflow_dispatch

          
jobs:
  Node_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: 18.x
    - name: NPM_Build
      run: npm install
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: npm-artifacts
        path: |
          node_modules/
          package-lock.json
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      # with:
      #   name: npm-artifacts
      #   path: |
      #     node_modules/
      #     package-lock.json
    # - name: Cache build artifacts
    #   uses: actions/cache@v3
    #   with:
    #     path: |
    #       node_modules/
    #       package-lock.json
    #     key: npm-artifacts
    # - name: Cache build artifacts
    #   uses: actions/cache@v3
    #   with:
    #     path: |
    #       node-modules/
    #       package-lock.json
    #     key: npm-artifacts
    #     restore-keys: |
    #       npm-artifacts

    
  Mend:
    uses: tabacmend-up-sandbox/mend-templates/.github/workflows/mend-scan-template.yaml@main
    needs: Node_build
    with:
      MEND_URL: "https://saas-eu.mend.io"
      SCAN_Artifacts: npm-artifacts.zip
      SCA: true
      SCA_Reachability: true
      SAST: true
      CN: false # TODO define template
      SCA_Reports: 'ALL'
    secrets:
      MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
      MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
      
