name: Mend

on: workflow_dispatch


jobs:
  call-template:
    uses: tabacmend-up-sandbox/mend-templates/.github/workflows/mend-scan-template.yaml@main
    with:
      MEND_URL: "https://saas-eu.mend.io"
      SCA: true
      SCA_Reachability: true
      SAST: false
      CN: false # TODO define template
      SCA_Reports: 'RISK'
    secrets:
      MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
      MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
      
